# Use this file to setup a conda environment for the project.
name: covid_cz_districts
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - spyder
  - pip
  - pip:
    - plotly_express
    - dash==1.12.0
    - dash-bootstrap-components
    - pandas
    - gunicorn